In [1]:
import cv2
cv2.__version__

'3.4.2'

In [2]:
# Template for computing SIFT features
import cv2
import numpy as np
from matplotlib import pyplot as plt


class SiftDetector():
    def __init__(self, norm="L2", params=None):
        self.detector=self.get_detector(params)
        self.norm=norm

    def get_detector(self, params):
        if params is None:
            params={}
            params["n_features"]=0
            params["n_octave_layers"]=3
            params["contrast_threshold"]=0.04
            params["edge_threshold"]=10
            params["sigma"]=1.6

        detector = cv2.xfeatures2d.SIFT_create(
                nfeatures=params["n_features"],
                nOctaveLayers=params["n_octave_layers"],
                contrastThreshold=params["contrast_threshold"],
                edgeThreshold=params["edge_threshold"],
                sigma=params["sigma"])

        return detector
class rotator():
    def __init__(self,image,angle,params=None):
        self.image = image
        self.angle = angle
        self.rotator = self.rotate(self.image,self.angle,params)

    def rotate(self,image, angle, params):
        # 获取图像尺寸
        (h, w) = image.shape[:2]
        # 若未指定旋转中心，则将图像中心设为旋转中心
        if(params is None):
            center = (w / 2, h / 2)
            scale = 1
        else:
            center = params["center"]
            scale = params["scale"]

        # 执行旋转
        M = cv2.getRotationMatrix2D(center, angle, scale)
        rotated = cv2.warpAffine(image, M, (w, h))
     
        # 返回旋转后的图像
        return rotated



if __name__ == '__main__':
    # 1. Read the colour image
    img = cv2.imread('NotreDame.jpg')
    # For task 2 only, rotate the image by 45 degrees
    rotator = rotator(img,-45)
    img_rotate = rotator.rotator

    # 2. Convert image to greyscale	
    gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    gray2= cv2.cvtColor(img_rotate,cv2.COLOR_BGR2GRAY)
    
    # 3. Initialise SIFT detector (with varying parameters)
    sift = SiftDetector().get_detector(None)
    
    # 4. Detect and compute SIFT features
    kp = sift.detect(gray,None)
    

    # 5. Visualise detected keypoints on the colour image 
    # img_1=cv2.drawKeypoints(img,kp,img,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
    # cv2.imwrite('sift_keypoints.jpg',img_1)

    # 6. compute sift key points and descriptor
    kp, des = sift.detectAndCompute(gray,None)
    print("number of descriptor is: ",len(des))
    print("descriptor values are: \n", des)
    # to reduce the number of key point to 1/4
    n_keypoints = len(des)//4
    print("1/4 is ",n_keypoints)
    sift = SiftDetector().get_detector({"n_features":0,
            "n_octave_layers":3,
            "contrast_threshold":0.1,
            "edge_threshold":8,
            "sigma":1.6})
    kp1 = sift.detect(gray,None)
    kp2 = sift.detect(gray2,None)
    print("kp1 number is ", len(kp1))
    print("kp2 number is ", len(kp2))
    print("kp is same as kp1 ? ",kp1==kp)

    cv2.drawKeypoints(img,kp1,img)#,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
    cv2.drawKeypoints(img_rotate,kp2,img_rotate)#,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
    cv2.imwrite('sift_keypoints_less.jpg',img)
    cv2.imwrite('sift_keypoints_less_part2.jpg',img_rotate)


    #extra......
    for angle in range(0,-180,-45):
        rotator = rotator(img,angle)
        img_rotate = rotator.rotator
        
        gray2= cv2.cvtColor(img_rotate,cv2.COLOR_BGR2GRAY)
        sift = SiftDetector().get_detector({"n_features":0,
                "n_octave_layers":3,
                "contrast_threshold":0.1,
                "edge_threshold":8,
                "sigma":1.6})
        kp1 = sift.detect(gray2,None)
        cv2.drawKeypoints(img_rotate,kp1,img_rotate)
        cv2.imwrite('degree {0}.jpg'.format(angle),img)

number of descriptor is:  5258
descriptor values are: 
 [[ 31.  11.  13. ...   4.  15.   1.]
 [  0.   0.   1. ...   0.   0.   1.]
 [  1.  45.   2. ...   0.   0.   4.]
 ...
 [ 29.   1.   1. ...   1.   0.  17.]
 [  3.   2.   1. ...   2.   7.   2.]
 [ 56.   3.   0. ...  81. 125.  86.]]
1/4 is  1314
kp1 number is  1321
kp2 number is  1293
kp is same as kp1 ?  False


TypeError: 'rotator' object is not callable