In [43]:
from sklearn import datasets
mnist = datasets.load_digits()
print(mnist.data.shape)
#need 1. data 2. target
print(mnist.target.shape)
print(mnist.images[0].shape)
print(mnist.data)

(1797, 64)
(1797,)
(8, 8)
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [74]:
import cv2,os,re,numpy
from matplotlib import pyplot as plt


def image_to_feature_vector(image, size=(64, 64)):
    # resize the image to a fixed size, then flatten the image into
    # a list of raw pixel intensities
    return cv2.resize(image, size).flatten()

numbers = {"eight":8,"five":5,"four":4,"nine":9,"one":1,"seven":7,"six":6,"three":3,"two":2,"zero":0}
data_array = []#numpy.array([])
class_array = []#numpy.array([])
count = 0
for filename in os.listdir("./data"):
    n = re.search('(.+?)_', filename)
    target = numbers[n.group(1)]
    image = cv2.imread("./data/{0}".format(filename))
    image_flatten = image_to_feature_vector(image)
#     if(data_array.size == 0):
#         data_array = image_flatten
#     else:
#         data_array = numpy.concatenate((data_array,image_flatten))
    #class_array = numpy.append(class_array,target)
    data_array.append(image_flatten)
    class_array.append(target)

    
    

In [60]:
print(len(data_array))
print(len(class_array))

5000
5000


In [75]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

(trainData, testData, trainLabels, testLabels) = train_test_split(data_array,
class_array, test_size=0.2, random_state=42)
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(trainData,trainLabels) 
acc = neigh.score(testData, testLabels)
print("accuracy is: ",acc)

predictions = neigh.predict(testData)
print ("Confusion matrix")
print(confusion_matrix(testLabels,predictions))

print("EVALUATION ON TESTING DATA")
print(classification_report(testLabels, predictions))



accuracy is:  0.954
Confusion matrix
[[116   0   0   0   0   0   0   0   0   0]
 [  0  94   0   0   0   0   0   1   0   0]
 [  0   1  93   0   0   0   0   1   1   0]
 [  0   1   1  88   0   1   1   3   1   0]
 [  0   1   0   0  87   0   0   0   0   5]
 [  0   1   0   2   0 113   1   0   0   1]
 [  1   0   0   0   0   2  81   0   0   0]
 [  0   1   0   0   1   1   0  94   0   0]
 [  0   3   0   3   1   1   2   0 102   0]
 [  1   1   1   0   2   0   1   1   0  86]]
EVALUATION ON TESTING DATA
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       116
           1       0.91      0.99      0.95        95
           2       0.98      0.97      0.97        96
           3       0.95      0.92      0.93        96
           4       0.96      0.94      0.95        93
           5       0.96      0.96      0.96       118
           6       0.94      0.96      0.95        84
           7       0.94      0.97      0.95        97
           8      

In [79]:
k = {1:95.1,2:94,3:95.4}

max(k, key=k.get)

<function dict.get(key, default=None, /)>